// Code generated by tools/gen-cvi-types.sh; DO NOT EDIT.
//
// Struct layouts for the CVITek multimedia uapi, generated from the vendor
// headers in meta-sophgo/recipes-kernel/soph-media against the riscv64 cross
// toolchain. See gen_types.go for what is generated and why.

package cvi

type MMFChn struct {
	EnModId  uint32
	S32DevId int32
	S32ChnId int32
}

type MMFBindDest struct {
	U32Num    uint32
	AstMmfChn [32]MMFChn
}

type Size struct {
	U32Width  uint32
	U32Height uint32
}

type Rect struct {
	S32X      int32
	S32Y      int32
	U32Width  uint32
	U32Height uint32
}

type VPSSGrpAttr struct {
	U32MaxW       uint32
	U32MaxH       uint32
	EnPixelFormat uint32
	StFrameRate   FrameRateCtrl
	U8VpssDev     uint8
	Pad_cgo_0     [3]byte
}

type VPSSChnAttr struct {
	U32Width      uint32
	U32Height     uint32
	EnVideoFormat uint32
	EnPixelFormat uint32
	StFrameRate   FrameRateCtrl
	BMirror       uint8
	BFlip         uint8
	U32Depth      uint32
	StAspectRatio AspectRatio
	StNormalize   VPSSNormalize
}

type VENCChnAttr struct {
	StVencAttr VENCAttr
	StRcAttr   VENCRcAttr
	StGopAttr  VENCGopAttr
}

type VENCAttr struct {
	EnType          uint32
	U32MaxPicWidth  uint32
	U32MaxPicHeight uint32
	U32BufSize      uint32
	U32Profile      uint32
	BByFrame        uint8
	U32PicWidth     uint32
	U32PicHeight    uint32
	BSingleCore     uint8
	BEsBufQueueEn   uint8
	BIsoSendFrmEn   uint8
	Pad_cgo_0       [1]byte
	StAttrH264e     VENCAttrH264
	Pad_cgo_1       [26]byte
}

type VENCRcAttr struct {
	EnRcMode  uint32
	StH264Cbr VENCH264Cbr
	Pad_cgo_0 [4]byte
}

type VENCGopAttr struct {
	EnGopMode uint32
	StNormalP VENCGopNormalP
	Pad_cgo_0 [8]byte
}

type VENCRecvPicParam struct {
	S32RecvPicNum int32
}

type VENCChnStatus struct {
	U32LeftPics         uint32
	U32LeftStreamBytes  uint32
	U32LeftStreamFrames uint32
	U32CurPacks         uint32
	U32LeftRecvPics     uint32
	U32LeftEncPics      uint32
	BJpegSnapEnd        uint8
	StVencStrmInfo      VENCStreamInfo
}

type VENCStreamEx struct {
	PstStream   *VENCStream
	S32MilliSec int32
	Pad_cgo_0   [4]byte
}

type VENCStream struct {
	PstPack           *VENCPack
	U32PackCount      uint32
	U32Seq            uint32
	StH264Info        VENCStreamInfoH264
	Pad_cgo_0         [12]byte
	StAdvanceH264Info VENCStreamAdvanceInfoH264
}

type VENCPack struct {
	U64PhyAddr uint64
	Pu8Addr    *uint8
	U32Len     uint32
	U64PTS     uint64
	BFrameEnd  uint8
	Pad_cgo_0  [3]byte
	DataType   [4]byte
	U32Offset  uint32
	U32DataNum uint32
	StPackInfo [8]VENCPackInfo
}

type VideoFrameInfo struct {
	StVFrame  VideoFrame
	U32PoolId uint32
	Pad_cgo_0 [4]byte
}

type VideoFrame struct {
	U32Width        uint32
	U32Height       uint32
	EnPixelFormat   uint32
	EnBayerFormat   uint32
	EnVideoFormat   uint32
	EnCompressMode  uint32
	EnDynamicRange  uint32
	EnColorGamut    uint32
	U32Stride       [3]uint32
	U64PhyAddr      [3]uint64
	Pu8VirAddr      [3]*uint8
	U32Length       [3]uint32
	S16OffsetTop    int16
	S16OffsetBottom int16
	S16OffsetLeft   int16
	S16OffsetRight  int16
	U32TimeRef      uint32
	U64PTS          uint64
	PPrivateData    *byte
	U32FrameFlag    uint32
	Pad_cgo_0       [4]byte
}

type AspectRatio struct {
	EnMode         uint32
	BEnableBgColor uint8
	U32BgColor     uint32
	StVideoRect    Rect
}

type FrameRateCtrl struct {
	S32SrcFrameRate int32
	S32DstFrameRate int32
}

type VPSSNormalize struct {
	BEnable  uint8
	Factor   [3]float32
	Mean     [3]float32
	Rounding uint32
}

type VENCPackInfo struct {
	U32PackType   [4]byte
	U32PackOffset uint32
	U32PackLength uint32
}

type VENCStreamInfo struct {
	EnRefType         uint32
	U32PicBytesNum    uint32
	U32PicCnt         uint32
	U32StartQp        uint32
	U32MeanQp         uint32
	BPSkip            uint8
	U32ResidualBitNum uint32
	U32HeadBitNum     uint32
	U32MadiVal        uint32
	U32MadpVal        uint32
	U32MseSum         uint32
	U32MseLcuCnt      uint32
	DPSNRVal          float64
}

type VENCSSEInfo struct {
	BSSEEn    uint8
	U32SSEVal uint32
}

type VENCAttrH264 struct {
	BRcnRefShareBuf uint8
	BSingleLumaBuf  uint8
}

type VENCH264Cbr struct {
	U32Gop           uint32
	U32StatTime      uint32
	U32SrcFrameRate  uint32
	Fr32DstFrameRate uint32
	U32BitRate       uint32
	BVariFpsEn       uint8
	Pad_cgo_0        [3]byte
}

type VENCGopNormalP struct {
	S32IPQpDelta int32
}

type VENCStreamInfoH264 struct {
	U32PicBytesNum     uint32
	U32Inter16x16MbNum uint32
	U32Inter8x8MbNum   uint32
	U32Intra16MbNum    uint32
	U32Intra8MbNum     uint32
	U32Intra4MbNum     uint32
	EnRefType          uint32
	U32UpdateAttrCnt   uint32
	U32StartQp         uint32
	U32MeanQp          uint32
	BPSkip             uint8
	Pad_cgo_0          [3]byte
}

type VENCStreamAdvanceInfoH264 struct {
	U32ResidualBitNum    uint32
	U32HeadBitNum        uint32
	U32MadiVal           uint32
	U32MadpVal           uint32
	DPSNRVal             float64
	U32MseLcuCnt         uint32
	U32MseSum            uint32
	StSSEInfo            [8]VENCSSEInfo
	U32QpHstgrm          [52]uint32
	U32MoveScene16x16Num uint32
	U32MoveSceneBits     uint32
}
