#!/bin/sh
# NanoKVM BMC Service

DAEMON="NanoKVM-Server"
PID_FILE="/var/run/${DAEMON}.pid"
LOGFILE="/var/log/${DAEMON}.log"

start() {
    start-stop-daemon -S -b -m -o -p "$PID_FILE" -O "$LOGFILE" -x "/kvmapp/server/${DAEMON}" && echo "OK" || echo "FAIL"
}

stop() {
    start-stop-daemon -K -q -o -p "$PID_FILE" -x "/kvmapp/server/${DAEMON}" && echo "OK" || echo "FAIL"
}

status() {
    start-stop-daemon -K -q -t -p "$PID_FILE" -x "/kvmapp/server/${DAEMON}" && echo "NanoKVM is running (PID $(cat "$PID_FILE"))" || echo "NanoKVM is not running"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        sleep 1
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
